; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

<<<<<<< HEAD

=======
>>>>>>> 4c1c309901fafda5a94426de8cfa24404ca17e73
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
<<<<<<< HEAD
upload_port = COM11
#monitor_port = COM11
monitor_speed = 115200

# Partition scheme to allow for LittleFS and large code
board_build.partitions = min_spiffs.csv

build_flags = 
    -DARDUINO_LITTLEFS_ENABLE
    -std=gnu++17

build_unflags = -std=gnu++11

lib_deps =
    # RFID and Sensors
    MFRC522
    ESP32Servo
    LiquidCrystal_I2C
    
    # Communication and Data
    ArduinoJson
    
    # MQTT Library (Replaces Redis)
    knolleary/PubSubClient @ ^2.8
    
    # Optional: SensESP (Keep if you are using its other features)
    # SensESP


=======
monitor_speed = 115200



lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.10
    madhephaestus/ESP32Servo @ ^3.0.5
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    bblanchon/ArduinoJson @ ^7.2.2
    PubSubClient.h
    PubSubClient @ ^2.8.0
>>>>>>> 4c1c309901fafda5a94426de8cfa24404ca17e73
